 spring.application.name=grocery-recommendation
server.port=1234
# MySQL DB
spring.datasource.url=jdbc:mysql://localhost:3306/grocery_db
spring.datasource.username=root
spring.datasource.password=indraja@28

# Hibernate ddl-auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# JWT
grocery.app.jwtSecret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
grocery.app.jwtExpirationMs=86400000


